import type { DisplayProfile } from './types'
import { VERIFIED_RAM_AV_CM01_ASPECT, VERIFIED_RAM_AV_CM01_SAMPLE } from './samples'

/**
 * Display profiles.
 *
 * RAM_AV_CM01 is locked to the verified MacBook → HDMI → AV-CM01 → RAM 12.4
 * Uconnect *browser* geometry. Those numbers are not the LCD native panel
 * resolution. RAM_12_4_PORTRAIT still matches a true portrait cockpit.
 */
export const DISPLAY_PROFILES: DisplayProfile[] = [
  {
    id: 'RAM_AUTO',
    vehicle: 'ram',
    label: 'RAM Auto',
    orientation: 'portrait',
    orientationMode: 'either',
    minWidth: 720,
    maxWidth: 2200,
    minHeight: 640,
    maxHeight: 2400,
    minAspect: 0.42,
    maxAspect: 1.95,
    layout: 'ram-auto',
    specificity: 0.58,
    adapterIds: ['av-cm01', 'avcm01', 'ram-hdmi'],
    safeArea: { top: 18, right: 16, bottom: 22, left: 16 },
    touchTarget: 56,
    uiScale: 1,
    bridgeHints: { portraitPanelTarget: 'ram-12-4' },
  },
  {
    id: 'RAM_12_4_PORTRAIT',
    vehicle: 'ram',
    label: 'RAM 12.4 Portrait',
    orientation: 'portrait',
    minWidth: 720,
    maxWidth: 1400,
    minHeight: 1280,
    maxHeight: 2400,
    minAspect: 0.45,
    maxAspect: 0.78,
    preferredAspect: 9 / 16,
    layout: 'ram-portrait',
    specificity: 1,
    safeArea: { top: 28, right: 18, bottom: 36, left: 18 },
    touchTarget: 64,
    uiScale: 1,
  },
  {
    id: 'RAM_AV_CM01',
    vehicle: 'ram',
    label: 'RAM AV-CM01',
    orientation: 'landscape',
    // Windowed sample is 1555×1081; ranges also cover Chrome fullscreen on the
    // same MacBook (inner grows toward 1728×1117) without exact equality.
    minWidth: 1400,
    maxWidth: 1800,
    preferredWidth: VERIFIED_RAM_AV_CM01_SAMPLE.innerWidth,
    minHeight: 980,
    maxHeight: 1180,
    preferredHeight: VERIFIED_RAM_AV_CM01_SAMPLE.innerHeight,
    minAspect: 1.32,
    maxAspect: 1.62,
    preferredAspect: VERIFIED_RAM_AV_CM01_ASPECT,
    minScreenWidth: 1650,
    maxScreenWidth: 1800,
    preferredScreenWidth: VERIFIED_RAM_AV_CM01_SAMPLE.screenWidth,
    minScreenHeight: 1050,
    maxScreenHeight: 1180,
    preferredScreenHeight: VERIFIED_RAM_AV_CM01_SAMPLE.screenHeight,
    minDevicePixelRatio: 1.7,
    maxDevicePixelRatio: 1.9,
    targetDevicePixelRatio: 1.8,
    layout: 'ram-hdmi-bridge',
    specificity: 1,
    adapterIds: ['av-cm01', 'avcm01', 'ram-hdmi'],
    bridgeHints: {
      hdmiLike: true,
      portraitPanelTarget: 'ram-12-4',
      typicalAspects: [VERIFIED_RAM_AV_CM01_ASPECT],
    },
    safeArea: { top: 16, right: 20, bottom: 18, left: 20 },
    touchTarget: 60,
    uiScale: 0.96,
  },
  {
    id: 'FORD_F250_12_LANDSCAPE',
    vehicle: 'ford',
    label: 'Ford F-250 12 Landscape',
    orientation: 'landscape',
    minWidth: 1100,
    maxWidth: 1680,
    minHeight: 640,
    maxHeight: 920,
    minAspect: 1.5,
    maxAspect: 1.75,
    preferredWidth: 1280,
    preferredHeight: 768,
    preferredAspect: 1280 / 768,
    layout: 'ford-landscape',
    specificity: 1,
    safeArea: { top: 22, right: 20, bottom: 18, left: 20 },
    touchTarget: 52,
    uiScale: 1,
  },
  {
    id: 'TESLA_MODEL_Y_LANDSCAPE',
    vehicle: 'tesla',
    label: 'Tesla Model Y Landscape',
    orientation: 'landscape',
    minWidth: 1680,
    maxWidth: 2600,
    minHeight: 980,
    maxHeight: 1700,
    minAspect: 1.48,
    maxAspect: 1.7,
    preferredWidth: 1920,
    preferredHeight: 1200,
    preferredAspect: 1920 / 1200,
    layout: 'tesla-landscape',
    specificity: 1,
    safeArea: { top: 14, right: 18, bottom: 16, left: 18 },
    touchTarget: 46,
    uiScale: 1.04,
  },
  {
    id: 'GENERIC_PORTRAIT',
    vehicle: 'generic',
    label: 'Generic Portrait',
    orientation: 'portrait',
    minWidth: 320,
    maxWidth: 1600,
    minHeight: 500,
    maxHeight: 2800,
    minAspect: 0.3,
    maxAspect: 0.95,
    layout: 'generic-portrait',
    specificity: 0.42,
    safeArea: { top: 20, right: 14, bottom: 24, left: 14 },
    touchTarget: 48,
    uiScale: 1,
  },
  {
    id: 'GENERIC_LANDSCAPE',
    vehicle: 'generic',
    label: 'Generic Landscape',
    orientation: 'landscape',
    minWidth: 500,
    maxWidth: 4000,
    minHeight: 320,
    maxHeight: 2200,
    minAspect: 1.05,
    maxAspect: 3.2,
    layout: 'generic-landscape',
    specificity: 0.42,
    safeArea: { top: 16, right: 16, bottom: 16, left: 16 },
    touchTarget: 48,
    uiScale: 1,
  },
]

export const PROFILE_BY_ID: Record<string, DisplayProfile> = Object.fromEntries(
  DISPLAY_PROFILES.map((profile) => [profile.id, profile]),
)

export function getProfileById(id: string): DisplayProfile | undefined {
  return PROFILE_BY_ID[id]
}

export const GENERIC_PROFILE_IDS = new Set(['GENERIC_PORTRAIT', 'GENERIC_LANDSCAPE'])
