import type { DisplayProfile } from './types'

/**
 * Initial display profiles.
 *
 * RAM native 12.4-inch pixels are intentionally unspecified. Until the
 * truck viewport is captured, RAM_12_4_PORTRAIT and RAM_AV_CM01 match
 * geometry *ranges* and HDMI-like aspect, not a fake exact resolution.
 */
export const DISPLAY_PROFILES: DisplayProfile[] = [
  {
    id: 'RAM_AUTO',
    vehicle: 'ram',
    label: 'RAM Auto',
    orientation: 'portrait',
    orientationMode: 'either',
    minWidth: 720,
    maxWidth: 2200,
    minHeight: 640,
    maxHeight: 2400,
    minAspect: 0.42,
    maxAspect: 1.95,
    layout: 'ram-auto',
    specificity: 0.58,
    adapterIds: ['av-cm01', 'avcm01', 'ram-hdmi'],
    safeArea: { top: 18, right: 16, bottom: 22, left: 16 },
    touchTarget: 56,
    uiScale: 1,
    bridgeHints: { portraitPanelTarget: 'ram-12-4' },
  },
  {
    id: 'RAM_12_4_PORTRAIT',
    vehicle: 'ram',
    label: 'RAM 12.4 Portrait',
    orientation: 'portrait',
    minWidth: 720,
    maxWidth: 1400,
    minHeight: 1280,
    maxHeight: 2400,
    minAspect: 0.45,
    maxAspect: 0.78,
    preferredAspect: 9 / 16,
    layout: 'ram-portrait',
    specificity: 1,
    safeArea: { top: 28, right: 18, bottom: 36, left: 18 },
    touchTarget: 64,
    uiScale: 1,
  },
  {
    id: 'RAM_AV_CM01',
    vehicle: 'ram',
    label: 'RAM AV-CM01',
    orientation: 'landscape',
    minWidth: 1180,
    maxWidth: 2048,
    minHeight: 640,
    maxHeight: 1200,
    minAspect: 1.7,
    maxAspect: 1.95,
    preferredAspect: 16 / 9,
    layout: 'ram-hdmi-bridge',
    specificity: 1,
    adapterIds: ['av-cm01', 'avcm01', 'ram-hdmi'],
    bridgeHints: {
      hdmiLike: true,
      portraitPanelTarget: 'ram-12-4',
      typicalAspects: [16 / 9, 1280 / 720, 1920 / 1080],
    },
    safeArea: { top: 16, right: 28, bottom: 18, left: 28 },
    touchTarget: 56,
    uiScale: 0.96,
  },
  {
    id: 'FORD_F250_12_LANDSCAPE',
    vehicle: 'ford',
    label: 'Ford F-250 12 Landscape',
    orientation: 'landscape',
    minWidth: 1100,
    maxWidth: 1680,
    minHeight: 640,
    maxHeight: 920,
    minAspect: 1.5,
    maxAspect: 1.75,
    preferredWidth: 1280,
    preferredHeight: 768,
    preferredAspect: 1280 / 768,
    layout: 'ford-landscape',
    specificity: 1,
    safeArea: { top: 22, right: 20, bottom: 18, left: 20 },
    touchTarget: 52,
    uiScale: 1,
  },
  {
    id: 'TESLA_MODEL_Y_LANDSCAPE',
    vehicle: 'tesla',
    label: 'Tesla Model Y Landscape',
    orientation: 'landscape',
    minWidth: 1680,
    maxWidth: 2600,
    minHeight: 980,
    maxHeight: 1700,
    minAspect: 1.48,
    maxAspect: 1.7,
    preferredWidth: 1920,
    preferredHeight: 1200,
    preferredAspect: 1920 / 1200,
    layout: 'tesla-landscape',
    specificity: 1,
    safeArea: { top: 14, right: 18, bottom: 16, left: 18 },
    touchTarget: 46,
    uiScale: 1.04,
  },
  {
    id: 'GENERIC_PORTRAIT',
    vehicle: 'generic',
    label: 'Generic Portrait',
    orientation: 'portrait',
    minWidth: 320,
    maxWidth: 1600,
    minHeight: 500,
    maxHeight: 2800,
    minAspect: 0.3,
    maxAspect: 0.95,
    layout: 'generic-portrait',
    specificity: 0.42,
    safeArea: { top: 20, right: 14, bottom: 24, left: 14 },
    touchTarget: 48,
    uiScale: 1,
  },
  {
    id: 'GENERIC_LANDSCAPE',
    vehicle: 'generic',
    label: 'Generic Landscape',
    orientation: 'landscape',
    minWidth: 500,
    maxWidth: 4000,
    minHeight: 320,
    maxHeight: 2200,
    minAspect: 1.05,
    maxAspect: 3.2,
    layout: 'generic-landscape',
    specificity: 0.42,
    safeArea: { top: 16, right: 16, bottom: 16, left: 16 },
    touchTarget: 48,
    uiScale: 1,
  },
]

export const PROFILE_BY_ID: Record<string, DisplayProfile> = Object.fromEntries(
  DISPLAY_PROFILES.map((profile) => [profile.id, profile]),
)

export function getProfileById(id: string): DisplayProfile | undefined {
  return PROFILE_BY_ID[id]
}

export const GENERIC_PROFILE_IDS = new Set(['GENERIC_PORTRAIT', 'GENERIC_LANDSCAPE'])
